#server port
server:
  port: 8003

#kafka config
kafka:
  bootstrap-servers: localhost:9092
  topic:
    create-task-dto: createTaskDto

#core-application url
core:
  application:
    url: http://localhost:8001

#username
username: dat

# password
password: 123456

#config log4j
logging:
  file: log/web-service-log.log